added jars to aws for convenience (#63)
* added jars to aws

* wait for binaries and upload jar on every build

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -99,43 +99,47 @@ deploy_script:
   - aws s3 cp %APPVEYOR_BUILD_FOLDER%\installed64\lib\ s3://brainflow-artifacts/%APPVEYOR_REPO_COMMIT%/lib64 --recursive
   # download files from travis using S3 create package and publish it
   - ps: >-
-      If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") {
-        # wait 30 minutes or until mac and linux binaries appear in s3
-        $lin = $false;
-        $osx = $false;
-        for ($i=0; $i -lt 30; $i++) {
-          aws s3 ls s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/linux_success;
-          $lin = $?;
-          aws s3 ls s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/osx_success;
-          $osx = $?
-          if($lin -and $osx) {break}
-          Start-Sleep -s 60;
-          echo "not found"
-        }
-        If ($lin -and $osx) {
-          write-output "Binaries found - running deployment"
-          New-Item $env:APPVEYOR_BUILD_FOLDER\linux -itemtype directory
-          New-Item $env:APPVEYOR_BUILD_FOLDER\osx -itemtype directory
-          aws s3 cp s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/linux/ $env:APPVEYOR_BUILD_FOLDER\linux\ --recursive
-          aws s3 cp s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/osx/ $env:APPVEYOR_BUILD_FOLDER\osx\ --recursive
+      # wait 30 minutes or until mac and linux binaries appear in s3
+      $lin = $false;
+      $osx = $false;
+      for ($i=0; $i -lt 30; $i++) {
+        aws s3 ls s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/linux_success;
+        $lin = $?;
+        aws s3 ls s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/osx_success;
+        $osx = $?
+        if($lin -and $osx) {break}
+        Start-Sleep -s 60;
+        echo "not found"
+      }
+      If ($lin -and $osx) {
+        write-output "Binaries found - running deployment"
+        New-Item $env:APPVEYOR_BUILD_FOLDER\linux -itemtype directory
+        New-Item $env:APPVEYOR_BUILD_FOLDER\osx -itemtype directory
+        aws s3 cp s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/linux/ $env:APPVEYOR_BUILD_FOLDER\linux\ --recursive
+        aws s3 cp s3://brainflow-artifacts/$env:APPVEYOR_REPO_COMMIT/osx/ $env:APPVEYOR_BUILD_FOLDER\osx\ --recursive
+        cd $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow
+        mvn package > mvn_final_stdout.txt
+        #upload .jars to aws
+        aws s3 cp %APPVEYOR_BUILD_FOLDER%\java-package\brainflow\target\ s3://brainflow-artifacts/%APPVEYOR_REPO_COMMIT%/jars --recursive
+
+        If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") {
           Copy-Item "$env:APPVEYOR_BUILD_FOLDER\linux\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib" -Recurse
           Copy-Item "$env:APPVEYOR_BUILD_FOLDER\osx\*" -Destination "$env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib" -Recurse
           ls $env:APPVEYOR_BUILD_FOLDER\python-package\brainflow\lib
           cd $env:APPVEYOR_BUILD_FOLDER\python-package
           python setup.py sdist bdist_wheel
           twine upload --skip-existing dist/*.whl --user OpenBCI --password $env:PYPI_PASSWORD
-          cd $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow
-          mvn package > mvn_final_stdout.txt
           cd $env:APPVEYOR_BUILD_FOLDER\tools
           .\github-release.exe release --user OpenBCI --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME
           .\github-release.exe upload --user OpenBCI --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME --name brainflow.jar --file $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\target\brainflow.jar
           .\github-release.exe upload --user OpenBCI --repo brainflow --tag $env:APPVEYOR_REPO_TAG_NAME --name brainflow-jar-with-dependencies.jar --file $env:APPVEYOR_BUILD_FOLDER\java-package\brainflow\target\brainflow-jar-with-dependencies.jar
         }
         Else {
-          write-output "Failed to wait for mac and linux libs"
+          write-output "Skip deployment for non tag"
         }
-      } Else {
-        write-output "Skip deployment for non tag"
+      }
+      Else {
+        write-output "Failed to wait for mac and linux libs"
       }
 
 on_finish:
